name: Build containers

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '(containers)')
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get base tag
        run: |
          echo "BASE_TAG=$(cat containers/base/metadata.json | jq -r '.version')" >> $GITHUB_ENV

      - name: Build and push base image
        uses: docker/build-push-action@v4
        with:
          context: "containers/base"
          push: true
          tags: |
            ghcr.io/henrywhitaker3/srep/base:latest
            ghcr.io/henrywhitaker3/srep/base:${{ env.BASE_TAG }}

      - name: Build scenario containers
        run: |
          for scenario in containers/*; do
            if [ $scenario != "containers/base" ]; then
              name=$(cat $scenario/metadata.json | jq -r '.name')
              tag=$(cat $scenario/metadata.json | jq -r '.version')
              image="ghcr.io/henrywhitaker3/srep/$name:$tag"

              set +e
              docker manifest inspect $image > /dev/null
              rc=$?
              set -e

              if [ $rc -eq 0 ]; then
                echo "$image already exists. Skipping..."
              else
                echo "Building $image"
                docker build $scenario --tag $image
                docker push $image
              fi
            fi
          done
